search: fix result counter
rero/ng-core pull request #322
Opened 2020-12-10 13:47 UTC by zannkukai

When a search result only 1 result, the result counter used always a
plural string. This commit fixes this behavior and get a singular '1
result' string a search return only 1 result.

Closes rero/ng-core#321

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2020-12-10 14:55 UTC, Garfield-fr commented on projects/rero/ng-core/src/lib/record/search/record-search.component.ts
> +      : this._translateService.stream('{{ total }} results', { total: this.total });
Consider zero results ?

2020-12-11 08:37 UTC, sebastiendeleze requested changes

2020-12-14 06:44 UTC, iGormilhit requested changes
Commit message proposition:

```
search: fix result counter

Adapts the text displaying the number of result when there's no result,
only one result or many results.

Closes rero/ng-core#321.
```

2020-12-14 08:40 UTC, sebastiendeleze approved these changes

2020-12-15 06:43 UTC, iGormilhit approved these changes

2020-12-16 06:54 UTC, merged