facet: added the possibility to customize the title
rero/ng-core pull request #375
Opened 2021-04-08 09:57 UTC by Garfield-fr

A new parameter "aggregationsTitle" has been added
to the configuration to allow the customization of the facet title.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Why are you opening this PR?

- allow the customization of the facet title

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2021-04-12 05:34 UTC, sebastiendeleze approved these changes

2021-04-12 05:34 UTC, sebastiendeleze commented on projects/rero/ng-core/src/lib/record/search/aggregation/aggregation.component.html
> +          </ng-template>
I think you can do something like this:

```typescript
{{ (aggregation.name || aggregation.key) | translate | ucfirst }}
```

2021-04-13 08:10 UTC, sebastiendeleze requested changes

2021-04-13 08:10 UTC, sebastiendeleze commented on projects/rero/ng-core/src/lib/record/search/record-search.component.ts
> +          name: this._aggregationName(key)
Could you change this statement as this:

```
name: aggr[key].name || this._aggregationName(key)
```

With this, we can set the name in the backend.

2021-04-13 13:11 UTC, jma approved these changes
Commit message: aggregation: make the name customizable

2021-04-14 06:43 UTC, sebastiendeleze approved these changes

2021-04-14 07:08 UTC, zannkukai approved these changes

2021-04-14 11:28 UTC, merged