search: move facets at bottom on small screen
rero/ng-core pull request #418
Opened 2021-07-09 11:50 UTC by zannkukai

On small screen, the facets (normally displayed on left sidebar) moves
to to bottom of the screen. So, the search result hits are mainly
displayed on small screen.

Co-authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2021-07-12 06:47 UTC, sebastiendeleze requested changes

2021-07-12 06:47 UTC, sebastiendeleze commented on projects/rero/ng-core/src/lib/record/search/record-search.component.html
> +      <div id="recordlist" class="col-sm-12 col-md-7 col-lg-9 order-sm-1 order-md-2">
I tested and think the following will be more appropriate:

```
<div id="recordlist" class="col-sm-12 col-md-7 col-lg-9 order-1 order-md-2">
```

(Same for the other column)

2021-07-22 05:51 UTC, iGormilhit requested changes
Commit message body proposition:

```
On small screen, the facets (normally displayed on left sidebar) moves
to the bottom of the screen. So, the search result hits are directly visible
on small screen.
```

2021-07-22 09:32 UTC, iGormilhit approved these changes

2021-07-27 08:58 UTC, sebastiendeleze requested changes
I tested and I think this can be improved as this:

```html
<div class="col-md-5 col-lg-3 mb-3 mb-md-0" *ngIf="showSearchInput"> // Line 36

<div *ngIf="resultsText$ | async as resultsText" class="col"> // Line 46

class="col-md-5 col-lg-3 order-2 order-md-1"> // Line 141

<div id="recordlist" class="col order-1 order-md-2"> // Line 208
```

Moreover, I discussed with @jma and @Garfield-fr and they think a better solution would be to have a toggle (hamburger) to show / hide aggregations.
This is a quick solution, but it will probably change in the future.

2021-08-23 10:11 UTC, jma approved these changes

2021-09-09 12:33 UTC, merged