search filter: fix translation
rero/ng-core pull request #520
Opened 2022-09-07 05:30 UTC by Garfield-fr

* Fixes translation on filter button.
* Cleans code.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

2022-09-07 06:52 UTC, PascalRepond approved these changes

2022-09-07 09:07 UTC, benerken approved these changes

2022-09-07 10:53 UTC, zannkukai approved these changes

2022-09-08 15:16 UTC, PascalRepond requested changes

2022-09-08 15:16 UTC, PascalRepond commented on projects/rero/ng-core/src/lib/record/search/aggregation/bucket-name.pipe.ts
> -    return (aggregationKey === 'language')
Deleting this prevents language codes to be translated in facets!

2022-09-12 07:49 UTC, PascalRepond approved these changes

2022-09-12 12:43 UTC, merged