files: add permissions
rero/ng-core pull request #555
Opened 2023-06-21 06:28 UTC by jma

* Fixes broken `ng` command such as `ng c`.
* Adds permissions support to the file component to hide action buttons.

Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2023-06-21 09:31 UTC, Garfield-fr approved these changes

2023-06-21 09:31 UTC, Garfield-fr commented on projects/rero/ng-core/src/lib/record/files/file/file.component.ts
Missing doc string

2023-06-21 09:31 UTC, Garfield-fr commented on projects/rero/ng-core/src/lib/record/files/files.component.html
> +    <button class="btn btn-sm btn-primary" *ngIf=canAdd (click)="manageFile(null)">
Is it necessary to have `*ngIf=canAdd` because there's already a div definition on the previous line?

2023-06-21 09:31 UTC, Garfield-fr commented on projects/rero/ng-core/src/lib/record/files/files.component.ts
> +                  console.log('tap1');
Remove this

2023-06-21 09:31 UTC, Garfield-fr commented on projects/rero/ng-core/src/lib/record/files/file/file.component.ts
> +    let obs$ = config.files.canUpdate
`ngOnDestroy: unsubscribe` on `obs$` ?

2023-06-22 12:14 UTC, zannkukai requested changes
most of my comments are suggestions.

I'm confused about the huge usage of Bootstrap classes into `ng-core` component : It doesn't allow child projects to override them. 
Instead of `<div class="ml-2 py-2 font-weight-bold text-primary border-bottom">` we should use `<div class="myComponentSpecialClass">` and apply default style on this class.

2023-06-22 12:14 UTC, zannkukai commented on projects/rero/ng-core/src/lib/record/files/file/file.component.ts
> +    obs$ = config.files.canDelete ? config.files.canDelete(this.record, this.file) : of({ can: false, message: '' });
I didn't know that it was possible to reassigned a new observable to a subscribed observable.

2023-06-22 12:14 UTC, zannkukai commented on projects/rero/ng-core/src/lib/record/files/files.component.html
> +    <h4 class="modal-title pull-left">{{ currentFile ? currentFile.key : ('Add a new file' | translate) }}</h4>
Wow 👍 Hawk eye !!!

2023-06-22 12:14 UTC, zannkukai commented on projects/rero/ng-core/src/lib/record/files/files.component.ts
> +            })
single instruction, could removed `{}` --> `canAdd$.subscribe((result: ActionStatus) => this.canAdd = result)`

2023-07-14 07:04 UTC, zannkukai approved these changes

2023-08-22 07:53 UTC, merged