translate: add spanish language
rero/ng-core pull request #556
Opened 2023-06-26 13:08 UTC by lauren-d

* Adds spanish language in translate service.

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2023-06-27 04:36 UTC, Garfield-fr approved these changes

2023-06-27 06:43 UTC, PascalRepond approved these changes

2023-06-28 07:29 UTC, zannkukai approved these changes

2023-06-29 07:06 UTC, jma requested changes
You probably need to modify also the `translate-loader.ts` file. Please find `fr.json` in the entire project.

2024-12-09 14:33 UTC, closed without merging