chore: fix the navigation
rero/ng-core pull request #614
Opened 2024-04-30 08:44 UTC by Garfield-fr

When a resource is added or modified, it is not always returned to the correct page. The editor now uses the previous url to redirect.

* Closes rero/rero-ils#3628.

2024-05-07 09:49 UTC, PascalRepond requested changes
This is not what was asked in https://github.com/rero/rero-ils/issues/3628. The redirect to the detailed view after saving a resource is totally fine as is. 

The problem was that the back button/browser function sometimes takes us to an editor view, sometimes not. This is not fixed by this PR.

2024-05-08 05:45 UTC, jma approved these changes

2024-05-14 09:47 UTC, PascalRepond approved these changes
Not-blocking: doesn't work for library editor beacuse it is not formly/jsonschema based. But this is not important as it is used very little.

2024-05-14 13:04 UTC, PascalRepond commented
After discussion, we decided to wait on this PR because it has unintended effects on the current workflows for professionnals, for example:
- Importing a document and saving it brings us straight back to the "import" window for this document
- Creating a document from the main menu brings us back to the main menu but we usually want to see the document we just created.
- Etc.

2025-05-20 12:41 UTC, closed without merging